### ISSUE TITLE
Saving and loading level progress/scores

### ISSUE THREAD

**Issue by Dmcdominic** [Dmcdominic/Toxic#35]
"Continue" and "New Game" options in main menu

**Comment by jianrongyu16** [comment]
highest completed level and global environment score

**Comment by Dmcdominic** [comment]
Implemented in commit [4a6c37e4f55b3ee2c52b2f1bd7a800c198b455ad](https://github.com/Dmcdominic/Enviro/commit/4a6c37e4f55b3ee2c52b2f1bd7a800c198b455ad).
Also updated in commit [0afbe702bed54bdb7f7715da2b440785c4b64c45](https://github.com/Dmcdominic/Enviro/commit/0afbe702bed54bdb7f7715da2b440785c4b64c45)
