### ISSUE TITLE
Foreground Objects Classes

### ISSUE THREAD

**Issue by jianrongyu16** [Dmcdominic/Toxic#4]
- [ ] Cloud [Michelle]
- [x] Tree, Protestors [Jianrong]
- [x] Rocks [Dominic]
- [x] River, Pond [Michelle]
- [x] Barrel [Dominic]
  - [x] Turnstile (to turn barrel) [Dominic]
- [x] Player [Dominic]
- [x] Bridge, Button [Jianrong]
- [x] Disposal [Alyssa]
- [x] Pit (that you can't walk on but objects can go on) [Dominic]
- [x] Railing (On the river tile) [Jianrong]

**Comment by Dmcdominic** [comment]
Closing this issue so we can manage foreground object classes with individual issues.
