### ISSUE TITLE
Environmental meter

### ISSUE THREAD

**Issue by jianrongyu16** [Dmcdominic/Toxic#6]

**Comment by riyuki15** [comment]
For vertical slice, the meter shows up on screen as a plain text. I plan to change it into a graphical representation (maybe a thermometer style) for future checkpoints.

**Comment by Dmcdominic** [comment]
Also need to add a global environmental meter, but this is blocked by #18

**Comment by Dmcdominic** [comment]
#18 is closed now, so the global environmental meter is unblocked.

**Comment by riyuki15** [comment]
done! (maybe I can polish the meter png later)
